version: '3.7'
services:

    ping:
        build: ping

    calc:
        build: calc

    soma:
        build: soma

    sub:
        build: sub

    nmult1:
    build: ./mult
    expose:
      - "8080"

    mult2:
    build: ./mult
    expose:
      - "8080"

    mult-backup:
    build: ./mult
    expose:
      - "8080"

    nginx:
    build: ./nginx
    ports:
      - "80:80"
        depends_on:
           - ping
           - calc
           - soma
           - sub
           - mult1
           - mult2
           - mult-backup
